/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Peach({ walking, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/Peach.glb')

  const actions = useRef()
  const [mixer] = useState(() => new THREE.AnimationMixer())
  useFrame((state, delta) => mixer.update(delta))
  useEffect(() => {
    actions.current = {
      PEACH_Defeat: mixer.clipAction(animations[0], group.current),
      PEACH_Defeat_2: mixer.clipAction(animations[1], group.current),
      PEACH_Idle: mixer.clipAction(animations[2], group.current),
      PEACH_Run: mixer.clipAction(animations[3], group.current),
      PEACH_Victory: mixer.clipAction(animations[4], group.current),
      PEACH_Victory_2: mixer.clipAction(animations[5], group.current),
      PEACH_Walking: mixer.clipAction(animations[6], group.current)
    }
    return () => animations.forEach(clip => mixer.uncacheClip(clip))
  }, [])

  useEffect(() => {
    mixer.stopAllAction()
    if (walking) {
      actions.current.PEACH_Walking.play()
    } else {
      actions.current.PEACH_Idle.play()
    }
  }, [walking])

  return (
    <group ref={group} {...props} dispose={null}>
      <scene>
        <group scale={[0.8, 0.8, 0.8]}>
          <primitive object={nodes.Bone} />
          <group>
            <skinnedMesh
              receiveShadow
              castShadow
              material={materials.Beige}
              geometry={nodes['Icosphere.000_0'].geometry}
              skeleton={nodes['Icosphere.000_0'].skeleton}
            />
            <skinnedMesh
              receiveShadow
              castShadow
              material={materials.Black}
              geometry={nodes['Icosphere.000_1'].geometry}
              skeleton={nodes['Icosphere.000_1'].skeleton}
            />
            <skinnedMesh
              receiveShadow
              castShadow
              material={materials.White}
              geometry={nodes['Icosphere.000_2'].geometry}
              skeleton={nodes['Icosphere.000_2'].skeleton}
            />
            <skinnedMesh
              receiveShadow
              castShadow
              material={materials.Brown}
              geometry={nodes['Icosphere.000_3'].geometry}
              skeleton={nodes['Icosphere.000_3'].skeleton}
            />
            <skinnedMesh
              receiveShadow
              castShadow
              material={materials.Green}
              geometry={nodes['Icosphere.000_4'].geometry}
              skeleton={nodes['Icosphere.000_4'].skeleton}
            />
            <skinnedMesh
              receiveShadow
              castShadow
              material={materials.Red}
              geometry={nodes['Icosphere.000_5'].geometry}
              skeleton={nodes['Icosphere.000_5'].skeleton}
            />
          </group>
        </group>
      </scene>
    </group>
  )
}
