// Auto-generated by https://github.com/react-spring/gltfjsx

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function BlueBerry(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/Blueberry.glb')

  const actions = useRef()
  const [mixer] = useState(() => new THREE.AnimationMixer())
  useFrame((state, delta) => mixer.update(delta))
  useEffect(() => {
    actions.current = {
      BLUEBERRY_Defeat: mixer.clipAction(animations[0], group.current),
      BLUEBERRY_Defeat_2: mixer.clipAction(animations[1], group.current),
      BLUEBERRY_Idle: mixer.clipAction(animations[2], group.current),
      BLUEBERRY_Run: mixer.clipAction(animations[3], group.current),
      BLUEBERRY_Victory: mixer.clipAction(animations[4], group.current),
      BLUEBERRY_Victory_2: mixer.clipAction(animations[5], group.current),
      BLUEBERRY_Walking: mixer.clipAction(animations[6], group.current)
    }
    actions.current.BLUEBERRY_Idle.play()
    return () => animations.forEach(clip => mixer.uncacheClip(clip))
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <group name="HumanArmature" scale={[7.01, 7.01, 7.01]}>
          <primitive object={nodes.Bone} />
          <group name="Icosphere">
            <skinnedMesh
              material={materials.Blue}
              geometry={nodes.Icosphere_0.geometry}
              skeleton={nodes.Icosphere_0.skeleton}
              name="Icosphere_0"
              castShadow
              receiveShadow
            />
            <skinnedMesh
              material={materials.Black}
              geometry={nodes.Icosphere_1.geometry}
              skeleton={nodes.Icosphere_1.skeleton}
              name="Icosphere_1"
              castShadow
              receiveShadow
            />
          </group>
        </group>
        <group name="EyeArmature" position={[0, 3.63, 0]}>
          <primitive object={nodes.Bone} />
          <group name="Eyes">
            <skinnedMesh
              material={materials.Black}
              geometry={nodes['Cylinder.001_0'].geometry}
              skeleton={nodes['Cylinder.001_0'].skeleton}
              name="Cylinder.001_0"
              castShadow
              receiveShadow
            />
            <skinnedMesh
              material={materials.White}
              geometry={nodes['Cylinder.001_1'].geometry}
              skeleton={nodes['Cylinder.001_1'].skeleton}
              name="Cylinder.001_1"
              castShadow
              receiveShadow
            />
          </group>
        </group>
        <group name="LeafArmature" position={[0, 4.94, 0]}>
          <primitive object={nodes.Bone} />
          <group name="Leaf">
            <skinnedMesh
              material={materials.DarkGreen}
              geometry={nodes.Cube_0.geometry}
              skeleton={nodes.Cube_0.skeleton}
              name="Cube_0"
              castShadow
              receiveShadow
            />
            <skinnedMesh
              material={materials.Green}
              geometry={nodes.Cube_1.geometry}
              skeleton={nodes.Cube_1.skeleton}
              name="Cube_1"
              castShadow
              receiveShadow
            />
          </group>
        </group>
      </scene>
    </group>
  )
}
